# Welcome to Jekyll!

# Website settings
title: Wojciech Prazuch
description: My humble personal webpage
keywords: Machine Learning, Data Science, Python
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://wprazuch.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: GitHub  # Be used at blog posts' author.
  first_name: Wojciech  # Be used at index page about me section.
  last_name: Prazuch  # Be used at index page about me section.
  avatar: /static/assets/img/landing/photo3.jpg  # upload your avatar at directory and edit it.
  github_username: wprazuch  # Leave blank if you don't have now
  linkedin_id: wprazuch # Leave blank if you don't have now
  facebook_username:   # Leave blank if you don't have now
  twitter_username: PrazuchWojciech  # Leave blank if you don't have now
  email: wojciechprazuch3@gmail.com  # Leave blank if you don't have now
  cv:  https://www.linkedin.com/in/wprazuch/ # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: I am a PhD Candidate at Silesian University of Technology at Gliwice. My main area 
        of research is Machine Learning for Healthcare, and I am active participant in many projects 
        related to that (DM me for more details). However, I am trying to be involved in many other areas as well, as I 
        personally find many wonderful ideas applied elsewhere to be applicable to other domains as well.
        I have 3 years of professional experience in Software Engineering, however, I found Machine Learning to bring me 
        much more enjoyment. I applied for PhD studies to dwelve deep into Machine Learning (Deep 
        Learning in particular), as my thesis is closely related to that topic. Currently, I work full time on 
        research, and this gives a lot of possibilities to improve every day.
  # Describe yourself.

# comment
# disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#   name: jalpc

# analytics
## google analytics
# ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
#   id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

